[package]
name = "opencl-tryout"
version = "0.1.0"
authors = ["lsunsi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3.1"
criterion-macro = "0.3.1"
ocl = "0.19.3"
